mode: 'development'
url:
  wanted: # 'https://www.wanted.co.kr/wdlist/518/895?country=kr&job_sort=job.latest_order&years=-1&locations=seoul.all'
    default: 'https://www.wanted.co.kr'
    nodejs: 'wdlist/518/895?country=kr&job_sort=job.latest_order&years=-1&locations=seoul.all'
db:
  host: ''
  user: ''
  password: ''
  database: ''
  port: 3306
limitRetryCount: 3
discord:
  clientId: 'client-id'
  clientToken: 'client-token'
